# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrado',
            old_name='cedula_identidad',
            new_name='cedula_de_identidad',
        ),
    ]
