# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20170206_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='actualizado',
        ),
        migrations.AlterField(
            model_name='registrado',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
