# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_auto_20170210_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
